- name: Install-platform
  remote_script: https://termbin.com/rea2g
  vars:
    foo: bar
  secrets:
    -  aws_creds
  retries: 1
  sub_tasks:
  - name: scale-up
    remote_script: https://termbin.com/f1g1
    trigger_rule: all_success
